spring:
    datasource:
        url: jdbc:mysql://27.148.190.53:39999/yykj_test?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull
        username: yykj_test
        password: SNxtzcZp7jXCwmxy
        #连接池的配置信息
        initialSize: 10
        minIdle: 10
        maxActive: 100
#        maxWait: 60000
#        timeBetweenEvictionRunsMillis: 60000
#        minEvictableIdleTimeMillis: 300000
#        validationQuery: SELECT 1 FROM DUAL
#        testWhileIdle: true
#        testOnBorrow: false
#        testOnReturn: false
#        poolPreparedStatements: true
#        maxPoolPreparedStatementPerConnectionSize: 20
    redis:
      open: true  # 是否开启redis缓存  true开启   false关闭
      database: 0
      host: 127.0.0.1
      port: 6379
      timeout: 6000 # 连接超时时长（毫秒）
      jedis:
        pool:
          max-active: 1000  # 连接池最大连接数（使用负值表示没有限制）
          max-wait: -1ms    # 连接池最大阻塞等待时间（使用负值表示没有限制）
          max-idle: 10      # 连接池中的最大空闲连接
          min-idle: 5       # 连接池中的最小空闲连接
yykj: 
  uploaddir: /www/wwwroot/img.test.wfwzs.com/
  visitprefix: http://img.test.wfwzs.com/
  appid: wx69b79496c0342beb
  secret: 7fd51669ca492019587c1a123c85c99c
  temppath: /tmp/
  giftemplatepath: /www/wwwroot/img.test.wfwzs.com/yykj/giftemplate/
  paynotifyurl: http://api.test.wfwzs.com/api/pay/notify
  imagePrefixUrl: https://yykj-public-image-1252188577.cos.ap-beijing.myqcloud.com/
